import mongoose from 'mongoose';

const IntegrationSchema = new mongoose.Schema({
    companyId: { type: String, required: true, index: true },
    platform: { type: String, required: true }, // shopify, woocommerce, magento, opencart, custom
    storeName: { type: String, required: true },
    
    credentials: {
        storeUrl: String,
        accessToken: String,
        consumerKey: String,
        consumerSecret: String,
        apiKey: String
    },

    webhookSecret: String, // Secret provided by platform or generated by us
    webhookUrl: String,    // The endpoint the platform should hit

    status: { 
        type: String, 
        enum: ['connected', 'error', 'disconnected'], 
        default: 'connected' 
    },
    
    health: {
        lastSync: Date,
        lastWebhook: Date,
        errorCount: { type: Number, default: 0 },
        lastError: String
    }
}, { timestamps: true });

// A company can have multiple stores on the same platform
IntegrationSchema.index({ companyId: 1, platform: 1, storeName: 1 }, { unique: true });

export default mongoose.model('Integration', IntegrationSchema);
